### ISSUE TITLE
Provider Plankton refactor

### ISSUE THREAD

**Issue by aaitor** [oceanprotocol/provider#22]
The idea is to list the things to refactor in the Provider side (sorted by priority):
 
- [x] Unify terms and use only asset_id. (#40)
- [x] Encapsulate Azure logic into osmosis class, before starting the independent osmosis project
- [x] Move acl and blockchain modules from provider-backend to ocean-web3 as a dependency.(#28 )
- [x] Move dao methods in provider-backend that are made for bigchaindb to the oceandb-bigchaindb-driver
- [x] Integrate with coverage & codacy tools (#17 )
- [x] Add more tests improving the code coverage
- [x] Resolve some of the main issues reported by Codacy: https://app.codacy.com/project/ocean-protocol/provider/dashboard
- Ocean-web3: (#44 )
  - [x] Resolve some of the main issues reported by Codacy: (#30 ) https://app.codacy.com/project/ocean-protocol/provider/dashboard
  - [ ] Add comments/doc strings
  - [ ] Rename OceanContractsWrapper to OceanKeeper
  - [ ] `OceanContractsWrapper`/`OceanKeeper` should encapsulate all functionality offered by the keeper
- [x] Use environment variables to fill the config of provider backend and oceandb-bigchaindb-driver and oceandb-mongo-driver to make it easy to run dockers and travis.
- [x] Pass addresses of contracts as environment variable to the provider.
- [x] Integrate bumpversion in all the projects to help in new realeases. 
  - [x] provider
  - [x] oceandb-driver-interface
  - [x] oceandb-mongodb-driver (https://github.com/oceanprotocol/oceandb-mongodb-driver/pull/8)
  - [x] oceandb-bigchaindb-driver (https://github.com/oceanprotocol/oceandb-bigchaindb-driver/pull/13)
  - [x] ocean-web3
- [x] Use markdown in project of oceandb instead of rst.(#31)
  - [x] oceandb-driver-interface
  - [x] oceandb-mongodb-driver
  - [x] oceandb-bigchaindb-driver
- [x] Add pypi and Codacy badges.
- [ ] Improve handling of keeper events. (#45 ) Options: 
  - Save a record of previous access requests in oceandb
  - Build the state of previous access requests by querying the keeper
- [ ] Move travis secure passwords in each project to a travis environment variable.(#43)
  - [ ] provider
  - [ ] oceandb-driver-interface
  - [ ] oceandb-mongodb-driver
  - [ ] oceandb-bigchaindb-driver
  - [ ] ocean-web3

After reviewing this, each entry will be an independent user story to be implemented in the following days.

**Comment by eruizgar91** [comment]
Most of this issues have been already solved. The issues not finished during this refactor are opened as new issues.
